import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import QueryClientProviderComponent from "./Components/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProviderComponent>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </QueryClientProviderComponent>
    </html>
  );
}
